big: 
    n_layers: [1 ,2, 3]
    n_units_l: [16,32, 64, 128, 256, 512]
    seed: 1
    episodes: 10000
    evaluation_episodes: 1000
    batch_size: [256, 128, 64, 32]
    gamma: 0.9
    inverting_gradients: true
    initial_memory_threshold: 500
    replay_memory_size: 10000
    epsilon_steps: 1000
    tau_actor: [0.1, 0.01, 0.001, 0.0001] 
    tau_actor_param: [0.1, 0.01, 0.001, 0.0001] 
    use_ornstein_noise: true
    learning_rate_actor: [0.1, 0.01, 0.001, 0.0001]
    learning_rate_actor_param: [0.1, 0.01, 0.001, 0.0001]
    epsilon_final: 0.01
    zero_index_gradients: false
    initialise_params: true
    scale_actions: true
    clip_grad: 10.0
    split: false
    indexed: false
    weighted: false
    average: false
    random_weighted: false
    save_freq: 0
    save_dir: "results/platform/"
    save_frames: false
    action_input_layer: 0
    title: "MPDDQN"
    
small: 
    n_layers: [1 ,2]
    n_units_l: [64, 128, 256]
    seed: 1
    episodes: 2500
    evaluation_episodes: 1000
    batch_size: [128, 64, 32]
    gamma: 0.9
    inverting_gradients: true
    initial_memory_threshold: 500
    replay_memory_size: 10000
    epsilon_steps: 1000
    tau_actor: [0.1, 0.01, 0.001] 
    tau_actor_param: [0.1, 0.01, 0.001] 
    use_ornstein_noise: true
    learning_rate_actor: [0.01, 0.001, 0.0001]
    learning_rate_actor_param: [0.01, 0.001, 0.0001]
    epsilon_final: 0.01
    zero_index_gradients: false
    initialise_params: true
    scale_actions: true
    clip_grad: 10.0
    split: false
    indexed: false
    weighted: false
    average: false
    random_weighted: false
    save_freq: 0
    save_dir: "results/platform/"
    save_frames: false
    action_input_layer: 0
    title: "MPDDQN"
